# -*- coding: utf-8 -*-
"""Untitled0.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x5Eb9Bu8s1ky6EPj9BhX4DvdX5bKhptR
"""

import numpy as np
import pandas as pd
import chart_studio.plotly as py
from plotly.offline import init_notebook_mode,iplot
init_notebook_mode(connected=True)
import plotly.graph_objs as go
from plotly.tools import FigureFactory as ff
import matplotlib.pyplot as plt
from wordcloud import WordCloud,STOPWORDS
from PIL import Image
import os
import warnings
warnings.filterwarnings("ignore")

iplot.init_notebook_mode()

vgsales=pd.read_csv("drive/MyDrive/Colab Notebooks/vgsales.csv")

vgsales.info()

d=vgsales.head(6)
colorscale = "plasma"
table = ff.create_table(d,colorscale=colorscale)
for i in range(len(table.layout.annotations)):
    table.layout.annotations[i].font.size = 9
table.show(renderer='colab')
iplot(table)

sales=vgsales.head(100)

import chart_studio

chart_studio.tools.set_credentials_file(username='username', api_key='api_key')
def configure_plotly_browser_state():
  import IPython
  display(IPython.core.display.HTML('''
        <script src="/static/components/requirejs/require.js"></script>
        <script>
          requirejs.config({
            paths: {
              base: '/static/base',
              plotly: 'https://cdn.plot.ly/plotly-latest.min.js?noext',
            },
          });
        </script>
        '''))

configure_plotly_browser_state()

traceNA = go.Scatter(
                    x = sales.Rank,
                    y = sales.NA_Sales,
                    mode = "markers",
                    name = "North America",
                    marker = dict(color = 'rgba(28, 149, 249, 0.8)',size=8),
                    text= sales.Name)

traceEU = go.Scatter(
                    x = sales.Rank,
                    y = sales.EU_Sales,
                    mode = "markers",
                    name = "Europe",
                    marker = dict(color = 'rgba(249, 94, 28, 0.8)',size=8),
                    text= sales.Name)
traceJP = go.Scatter(
                    x = sales.Rank,
                    y = sales.JP_Sales,
                    mode = "markers",
                    name = "Japan",
                    marker = dict(color = 'rgba(150, 26, 80, 0.8)',size=8),
                    text= sales.Name)
traceOS = go.Scatter(
                    x = sales.Rank,
                    y = sales.Other_Sales,
                    mode = "markers",
                    name = "Other",
                    marker = dict(color = 'lime',size=8),
                    text= sales.Name)

data = [traceNA, traceEU,traceJP,traceOS]
layout = dict(title = 'North America, Europe, Japan and Other Sales of Top 100 Video Games',
              xaxis= dict(title= 'Rank',ticklen= 5,zeroline= False,zerolinewidth=1,gridcolor="white"),
              yaxis= dict(title= 'Sales(In Millions)',ticklen= 5,zeroline= False,zerolinewidth=1,gridcolor="white",),
              paper_bgcolor='rgb(243, 243, 243)',
              plot_bgcolor='rgb(243, 243, 243)' )
fig = dict(data = data, layout = layout)
iplot(fig)

